SELECT afk_channel_id,
       afk_timeout,
       application_id,
       banner,
       default_message_notifications,
       description,
       discovery_splash,
       explicit_content_filter,
       features,
       icon,
       id,
       joined_at,
       large,
       max_members,
       max_presences,
       max_video_channel_users,
       mfa_level,
       name,
       nsfw_level,
       owner_id,
       owner,
       permissions,
       preferred_locale,
       premium_progress_bar_enabled,
       premium_subscription_count,
       premium_tier,
       rules_channel_id,
       splash,
       system_channel_flags,
       system_channel_id,
       unavailable,
       vanity_url_code,
       verification_level,
       widget_channel_id,
       widget_enabled
FROM guilds
WHERE id = $1