SELECT id,
       message_id,
       author_icon_url,
       author_name,
       author_proxy_icon_url,
       author_url,
       color,
       description,
       footer_icon_url,
       footer_proxy_icon_url,
       footer_text,
       image_height,
       image_proxy_url,
       image_url,
       image_width,
       kind,
       provider_name,
       provider_url,
       thumbnail_height,
       thumbnail_proxy_url,
       thumbnail_url,
       thumbnail_width,
       timestamp,
       title,
       url,
       video_height,
       video_proxy_url,
       video_url,
       video_width
FROM embeds
WHERE message_id = $1;